import { test, expect } from '@playwright/test';

test.beforeEach(async ({ page }) => {
    await page.goto('/')
    await page.getByRole('button', { name: "OWNERS" }).click()
    await page.getByRole('link', { name: "SEARCH" }).click()
})

test('Select the desired date in the calendar', async ({ page }) => {
    await page.getByRole('link', { name: 'Harold Davis' }).click()
    await page.getByRole('button', { name: 'Add New Pet' }).click()
    await expect(page.locator('#owner_name')).toHaveValue('Harold Davis')
    await expect(page.locator('#name + span')).toHaveClass(/glyphicon-remove/)
    await page.getByRole('textbox', { name: 'Name' }).fill('Tom')
    await expect(page.locator('#name + span')).toHaveClass(/glyphicon-ok/)
    await page.getByRole('button', { name: 'Open calendar' }).click()
    await page.getByRole('button', { name: 'Choose month and year' }).click()  
    await page.getByRole('button', {name: 'Previous 24 years'}).click()
    await page.getByText('2014').click()
    await page.getByText('MAY').click()
    await page.getByText('2', { exact: true }).click()
    await expect(page.locator('[name="birthDate"]')).toHaveValue('2014/05/02')
    await page.locator('[name="pettype"]').selectOption('dog')
    await page.getByRole('button', { name: 'Save Pet' }).click()
    const petsList = page.locator('app-pet-list').filter({ hasText: 'Tom' })
    await expect(petsList.locator('dt', { hasText: 'Name' }).locator('+ dd')).toHaveText('Tom')
    await expect(petsList.locator('dt', { hasText: 'Birth Date' }).locator('+ dd')).toHaveText('2014-05-02')
    await expect(petsList.locator('dt', { hasText: 'Type' }).locator('+ dd')).toHaveText('dog')
    await petsList.getByRole('button', { name: 'Delete Pet' }).click()
    await expect(petsList).toHaveCount(0)
})

test('Select the dates of visits and validate dates order', async ({ page }) => {
    await page.getByRole('link', { name: 'Jean Coleman' }).click()
    const samanthaPetSection = page.locator('app-pet-list', { hasText: 'Samantha' })
    await samanthaPetSection.getByRole('button', { name: 'Add Visit' }).click()
    await expect(page.getByRole('heading', { name: 'New Visit' })).toBeVisible()
    await expect(page.getByRole('row', { name: 'Samantha' }).getByRole('cell').first()).toHaveText('Samantha')
    await expect(page.getByRole('row', { name: 'Samantha' }).getByRole('cell').last()).toHaveText('Jean Coleman')
    await page.getByRole('button', { name: 'Open calendar'}).click()
    await page.locator('.mat-calendar-body-today').click()
    const date = new Date()
    const currentDay = date.toLocaleString('en-US', { day: '2-digit' })
    const currentMonth = date.toLocaleString('en-US', { month: '2-digit' })
    const currentYear = date.getFullYear()
    const expectedDateFormatted = `${currentYear}/${currentMonth}/${currentDay}`
    await expect(page.locator('.mat-datepicker-input')).toHaveValue(expectedDateFormatted)
    await page.locator('[name="description"]').fill('Dermatologist visit')
    await page.getByRole('button', { name: 'Add Visit' }).click()
    const samanthaVisitRow = samanthaPetSection.locator('app-visit-list').getByRole('row').nth(1)
    const visitDate = `${currentYear}-${currentMonth}-${currentDay}`
    await expect(samanthaVisitRow.getByRole('cell').first()).toHaveText(visitDate)
    await samanthaPetSection.getByRole('button', { name: 'Add Visit' }).click()
    await page.getByRole('button', { name: 'Open calendar' }).click()
    date.setDate(date.getDate() - 45)
    const previousDate = `${(date.toLocaleString('en-US', { month: '2-digit' }))} ${(date.getFullYear())}`
    let currentMonthAndYear = await page.getByRole('button', { name: 'Choose month and year'}).textContent()
    const previousDay = (date.getDate()).toString()

    while (!currentMonthAndYear?.includes(previousDate)) {
        await page.getByRole('button', { name: 'Previous month' }).click()
        currentMonthAndYear = await page.getByRole('button', { name: 'Choose month and year'}).textContent()
    }

    await page.locator('.mat-calendar-body-cell').getByText(previousDay, { exact: true }).click()
    await page.locator('[name="description"]').fill('Massage therapy')
    await page.getByRole('button', { name: 'Add Visit' }).click()
    const samanthaVisits = samanthaPetSection.locator('app-visit-list')
    await expect(samanthaVisits.getByRole('row', { name: 'Massage therapy'} )).toBeVisible()
    const mostRecentVisitDate = await samanthaVisitRow.getByRole('cell').first().textContent()
    const previousVisitRow = samanthaPetSection.locator('app-visit-list').getByRole('row').nth(2)
    const earlierVisitDate = await previousVisitRow.getByRole('cell').first().textContent()
    const ealierDate = new Date(earlierVisitDate!)
    const mostRecentDate = new Date(mostRecentVisitDate!)
    expect(ealierDate < mostRecentDate).toBeTruthy()
    await samanthaVisits.getByRole('row', { name: 'Dermatologist visit' }).getByRole('button', { name: 'Delete Visit' }).click()
    await samanthaVisits.getByRole('row', { name: 'Massage therapy' }).getByRole('button', { name: 'Delete Visit' }).click()
    await expect(samanthaVisits.getByRole('row', { name: 'Dermatologist visit' })).not.toBeVisible()
    await expect(samanthaVisits.getByRole('row', { name: 'Massage therapy' })).not.toBeVisible()
})