import { test, expect } from '@playwright/test';

test.beforeEach( async({page}) => {
  await page.goto('/')
  await page.getByRole('link', { name: 'Pet Types' }).click()
  await page.waitForLoadState('networkidle')
  let petTypeTitle = await page.getByRole('heading', {name: 'Pet Type'}).textContent()
  expect(petTypeTitle).toEqual('Pet Types')
})

test.describe('Input fields', () => {
    test('Update pet type', async ({page}) => {
        await page.locator('table').getByRole('row', {name: 'cat'})
            .getByRole('button', { name: 'Edit' }).click()
        await expect(page.locator('h2')).toHaveText('Edit Pet Type')
        let petInputEdition = page.locator('app-pettype-edit input[name="name"]')
        await petInputEdition.click()
        await petInputEdition.clear()
        await petInputEdition.pressSequentially('rabbit')
        await page.locator('button', {hasText: 'Update'}).click()
        await page.waitForLoadState('networkidle')
        let newInputValue = await page.locator('app-pettype-list input').first().inputValue()
        expect(newInputValue).toEqual('rabbit')
        await page.locator('table').getByRole('row', {name: 'rabbit'})
            .getByRole('button', { name: 'Edit' }).click()
        petInputEdition = page.locator('app-pettype-edit input[name="name"]')
        await petInputEdition.click()
        await petInputEdition.clear()
        await petInputEdition.pressSequentially('cat')
        await page.locator('button', {hasText: 'Update'}).click()
        await page.waitForLoadState('networkidle')
        newInputValue = await page.locator('app-pettype-list input').first().inputValue()
        expect(newInputValue).toEqual('cat')
    })
    
    test('Cancel pet type update', async ({page}) => {
        await page.locator('table').getByRole('row', {name: 'dog'})
            .getByRole('button', { name: 'Edit' }).click()
        let petInputEdition = page.locator('app-pettype-edit input[name="name"]')
        await petInputEdition.click()
        await petInputEdition.clear()
        await petInputEdition.pressSequentially('moose')
        expect(petInputEdition).toHaveValue('moose')
        await page.locator('button', {hasText: 'Cancel'}).click()
        await page.waitForLoadState('networkidle')
        expect(page.locator('table').getByRole('row', { name: 'dog' })).toBeVisible()
    })

    test('Validation of Pet type name is required', async ({page}) => {
        await page.locator('table').getByRole('row', {name: 'lizard'})
            .getByRole('button', { name: 'Edit' }).click()
        let petInputEdition = page.locator('app-pettype-edit input[name="name"]')
        await petInputEdition.click()
        await petInputEdition.clear()
        const errorMessage = await page.locator('.help-block').textContent()
        expect(errorMessage).toEqual('Name is required')
        await page.locator('button', {hasText: 'Update'}).click()
        const editPetTypeTitle = await page.locator('h2', {hasText: 'Edit Pet Type'}).textContent()
        expect(editPetTypeTitle).toEqual('Edit Pet Type')
        await page.locator('button', {hasText: 'Cancel'}).click()
        await page.waitForLoadState('networkidle')
        const petTypeTitle = await page.locator('h2', {hasText: 'Pet Types'}).textContent()
        expect(petTypeTitle).toEqual('Pet Types')
    })
})